name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Basic Checks
        run: |
          if [ ! -f "requirements.txt" ] && [ ! -f "backend/requirements.txt" ]; then echo "requirements.txt not found"; exit 1; fi
          if [ ! -f "backend/Dockerfile" ]; then echo "Backend Dockerfile not found"; exit 1; fi
          if [ ! -f "frontend/Dockerfile" ]; then echo "Frontend Dockerfile not found"; exit 1; fi
          if [ -f ".env" ]; then echo "WARNING: .env file accidentally committed!"; exit 1; fi

